apiVersion: v1
kind: Pod
metadata:
  name: tls-debugger
  namespace: prod
spec:
  containers:
  - name: tcpdump
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW